[package]
name = "raytrace_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.10"
rand = "0.8.5"
crossterm = "0.27.0"
syscalls = "0.6.15"
log = "0.4.20"
ordered-float = "4.2.0"
